fix custom scripts during update

diff --git a/iptvplayer-fork.patch b/iptvplayer-fork.patch
--- a/iptvplayer-fork.patch
+++ b/iptvplayer-fork.patch
@@ -1,6 +1,6 @@
 diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/components/configbase.py ./IPTVPlayer/components/configbase.py
 --- /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/components/configbase.py	2015-12-27 07:42:31.328793000 +0100
-+++ ./IPTVPlayer/components/configbase.py	2015-12-29 07:20:46.706805999 +0100
++++ ./IPTVPlayer/components/configbase.py	2016-01-12 13:00:13.286698000 +0100
 @@ -8,10 +8,9 @@
  ###################################################
  # LOCAL import
@@ -29,7 +29,7 @@ diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVP
          elif isinstance(currItem, ConfigText):
 diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/components/iptvconfigmenu.py ./IPTVPlayer/components/iptvconfigmenu.py
 --- /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/components/iptvconfigmenu.py	2015-12-16 10:43:24.788841774 +0100
-+++ ./IPTVPlayer/components/iptvconfigmenu.py	2015-12-29 07:20:46.714805999 +0100
++++ ./IPTVPlayer/components/iptvconfigmenu.py	2016-01-12 13:00:13.290695999 +0100
 @@ -7,12 +7,11 @@
  ###################################################
  # LOCAL import
@@ -238,10 +238,10 @@ diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVP
          player = config.plugins.iptvplayer.NaszPlayer
          alternativePlayer = config.plugins.iptvplayer.NaszPlayer
 diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/components/iptvextmovieplayer.py ./IPTVPlayer/components/iptvextmovieplayer.py
---- /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/components/iptvextmovieplayer.py	2015-12-01 20:55:07.046977999 +0100
-+++ ./IPTVPlayer/components/iptvextmovieplayer.py	2015-12-29 07:20:46.714805999 +0100
-@@ -1369,7 +1369,7 @@
-                 
+--- /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/components/iptvextmovieplayer.py	2016-01-03 07:53:12.145217001 +0100
++++ ./IPTVPlayer/components/iptvextmovieplayer.py	2016-01-12 13:00:13.294693999 +0100
+@@ -1372,7 +1372,7 @@
+             
              if config.plugins.iptvplayer.aac_software_decode.value:
                  cmd += ' -a -p 10'
 -            elif config.plugins.iptvplayer.plarform.value in ('mipsel', 'armv7'):
@@ -250,8 +250,8 @@ diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVP
              audioTrackIdx = self.metaHandler.getAudioTrackIdx()
              printDBG(">>>>>>>>>>>>>>>>>>>>>>>> audioTrackIdx[%d]" % audioTrackIdx)
 diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/components/iptvplayerwidget.py ./IPTVPlayer/components/iptvplayerwidget.py
---- /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/components/iptvplayerwidget.py	2015-12-16 10:43:24.788841774 +0100
-+++ ./IPTVPlayer/components/iptvplayerwidget.py	2015-12-29 07:20:46.722805999 +0100
+--- /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/components/iptvplayerwidget.py	2015-12-29 21:00:23.427137448 +0100
++++ ./IPTVPlayer/components/iptvplayerwidget.py	2016-01-12 13:00:13.298691999 +0100
 @@ -11,6 +11,10 @@
  from urllib import quote as urllib_quote
  
@@ -322,9 +322,31 @@ diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVP
                  return
              elif ret[1] == "IPTVDM":
                  self.runIPTVDM(self.selectHost)
+diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/iptvupdate/custom/xxx.sh ./IPTVPlayer/iptvupdate/custom/xxx.sh
+--- /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/iptvupdate/custom/xxx.sh	1970-01-01 01:00:00.000000000 +0100
++++ ./IPTVPlayer/iptvupdate/custom/xxx.sh	2016-01-03 07:53:14.919829001 +0100
+@@ -0,0 +1,17 @@
++#!/bin/sh
++cp $1/iptvupdate/custom/xxx.sh $2/iptvupdate/custom/xxx.sh
++status=$?
++if [ $status -ne 0 ]; then
++	echo "B³¹d krytyczny. Plik $0 nie mo¿e zostaæ skopiowany, error[$status]."
++	exit 1	
++fi
++cp $1/hosts/hostXXX.py $2/hosts/
++cp $1/icons/logos/XXXlogo.png $2/icons/logos/
++cp $1/icons/PlayerSelector/XXX*.png $2/icons/PlayerSelector/
++status=$?
++if [ $status -ne 0 ]; then
++	echo "Uwaga nie uda-o sià skopiowaŠ XXX, error[$status]."
++	exit 0
++fi
++echo "Wykonywanie $0 zako½czone sukcesem."
++exit 0
+\ No newline at end of file
 diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/iptvupdate/updatemainwindow.py ./IPTVPlayer/iptvupdate/updatemainwindow.py
 --- /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/iptvupdate/updatemainwindow.py	2015-12-27 07:42:31.332790999 +0100
-+++ ./IPTVPlayer/iptvupdate/updatemainwindow.py	2015-12-29 07:20:46.722805999 +0100
++++ ./IPTVPlayer/iptvupdate/updatemainwindow.py	2016-01-12 13:00:13.310686000 +0100
 @@ -19,7 +19,7 @@
  from Plugins.Extensions.IPTVPlayer.libs.pCommon             import common
  from Plugins.Extensions.IPTVPlayer.components.iptvplayerinit import TranslateTXT as _
@@ -352,7 +374,7 @@ diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVP
          self["list"].setSelectionState(enabled = False)
 diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/keymap.xml ./IPTVPlayer/keymap.xml
 --- /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/keymap.xml	2015-11-11 07:16:27.439257999 +0100
-+++ ./IPTVPlayer/keymap.xml	2015-12-29 07:20:46.722805999 +0100
++++ ./IPTVPlayer/keymap.xml	2016-01-12 13:00:13.310686000 +0100
 @@ -25,4 +25,23 @@
                  <key id="KEY_RED"   mapto="videooptions" flags="m" />
                  <key id="KEY_MENU"  mapto="menu"         flags="m" />
@@ -380,11 +402,14 @@ diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVP
 \ No newline at end of file
 diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/locale/pl/LC_MESSAGES/IPTVPlayer.po ./IPTVPlayer/locale/pl/LC_MESSAGES/IPTVPlayer.po
 --- /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/locale/pl/LC_MESSAGES/IPTVPlayer.po	2015-12-10 10:58:15.215665999 +0100
-+++ ./IPTVPlayer/locale/pl/LC_MESSAGES/IPTVPlayer.po	2015-12-29 16:14:57.027137448 +0100
-@@ -14,6 +14,57 @@
++++ ./IPTVPlayer/locale/pl/LC_MESSAGES/IPTVPlayer.po	2016-01-12 21:21:32.304050995 +0100
+@@ -14,6 +14,60 @@
  "Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
  "X-Poedit-SearchPath-0: ../plugin\n"
  
++msgid "Starting custom script"
++msgstr "Uruchamiam skrypt "
++
 +msgid "IPTV Player"
 +msgstr "Odtwarzacz IPTV"
 +
@@ -439,7 +464,7 @@ diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVP
  msgid "Watch video materials from IPTV services"
  msgstr "OglÄ…danie materiaÅ‚Ã³w z serwisÃ³w IPTV"
  
-@@ -57,7 +108,7 @@
+@@ -57,7 +111,7 @@
  msgstr "Pobieranie listy..."
  
  msgid "Configure host"
@@ -448,7 +473,7 @@ diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVP
  
  msgid "Info"
  msgstr "Informacje"
-@@ -269,7 +320,7 @@
+@@ -269,7 +323,7 @@
  msgstr "Platforma"
  
  msgid "Services configuration"
@@ -459,7 +484,7 @@ diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVP
  msgstr "ChroniÄ‡ wtyczkÄ™ kodem pin"
 diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/plugin.py ./IPTVPlayer/plugin.py
 --- /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/plugin.py	2015-11-17 06:34:21.247824000 +0100
-+++ ./IPTVPlayer/plugin.py	2015-12-29 07:20:46.722805999 +0100
++++ ./IPTVPlayer/plugin.py	2016-01-12 13:00:13.342670000 +0100
 @@ -73,7 +73,9 @@
      #print config.plugins.iptvplayer.rtmpdumppath.value
      #print config.plugins.iptvplayer.f4mdumppath.value
@@ -472,8 +497,8 @@ diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVP
      elif IPTVPlayerNeedInit():
          session.openWithCallback(boundFunction(doRunMain, session), IPTVSetupMainWidget, True)
 diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/setup/iptvsetupimpl.py ./IPTVPlayer/setup/iptvsetupimpl.py
---- /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/setup/iptvsetupimpl.py	2015-12-27 07:42:31.336788999 +0100
-+++ ./IPTVPlayer/setup/iptvsetupimpl.py	2015-12-29 07:20:46.726805999 +0100
+--- /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/setup/iptvsetupimpl.py	2016-01-03 07:53:12.145217001 +0100
++++ ./IPTVPlayer/setup/iptvsetupimpl.py	2016-01-12 13:00:13.342670000 +0100
 @@ -7,7 +7,7 @@
  from Plugins.Extensions.IPTVPlayer.setup.iptvsetuphelper     import CBinaryStepHelper, CCmdValidator, SetupDownloaderCmdCreator
  from Plugins.Extensions.IPTVPlayer.components.iptvplayerinit import TranslateTXT as _
@@ -593,7 +618,7 @@ diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVP
              elif 'GStreamer Core Library version ' in data: 
                  return True,False
              else: 
-@@ -228,6 +240,10 @@
+@@ -227,6 +240,10 @@
                  self.gstreamerVersion = "1.0"
              elif 'libgstbase-0.10.so' in dataTab[-1]:
                  self.gstreamerVersion = "0.10"
@@ -604,7 +629,7 @@ diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVP
              elif ' version 1.' in dataTab[-1]:
                  self.gstreamerVersion = "1.0"
              elif ' version 0.' in dataTab[-1]:
-@@ -338,7 +354,9 @@
+@@ -337,7 +354,9 @@
          def _detectValidator(code, data):
              if self.binaryInstalledSuccessfully: self.stepHelper.setInstallChoiseList( self._uchardetInstallChoiseList2 )
              else: self.stepHelper.setInstallChoiseList( self._uchardetInstallChoiseList )
@@ -617,7 +642,7 @@ diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVP
              sts, retPath = False, ""
 diff -Naur -X ./exclude.pats /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/tools/iptvtools.py ./IPTVPlayer/tools/iptvtools.py
 --- /home/j00zek/iptvplayer-GitLab-master-version/IPTVPlayer/tools/iptvtools.py	2015-12-20 06:49:33.986133998 +0100
-+++ ./IPTVPlayer/tools/iptvtools.py	2015-12-29 07:20:46.726805999 +0100
++++ ./IPTVPlayer/tools/iptvtools.py	2016-01-12 13:00:13.350665999 +0100
 @@ -47,7 +47,7 @@
      return nice
      
